Pb de detection des gcc.

diff --git a/alliance/src/distrib/mkasim b/alliance/src/distrib/mkasim
--- a/alliance/src/distrib/mkasim
+++ b/alliance/src/distrib/mkasim
@@ -3,7 +3,7 @@
 # Copyright (C) 2004 Jean-Paul Chaput <Jean-Paul.Chaput@lip6.fr>
 # License: GPL (http://www.gnu.org/copyleft/gpl.html)
 #
-# $Id: mkasim,v 1.2 2004/07/23 23:02:18 alliance Exp $
+# $Id: mkasim,v 1.3 2004/07/23 23:49:35 alliance Exp $
 #
 # /------------------------------------------------------------------\
 # |                                                                  |
@@ -169,29 +169,23 @@
  guessArch ()
  {
    case $1 in
-     "Linux.RH71")  if which gcc > /dev/null 2>&1; then
-                       TARGET=$LINUX_RH71_TARGET
-                          CXX=$LINUX_RH71_CXX
-                           CC=$LINUX_RH71_CC
-                    fi
-                    ;;
-     "Linux.FC2")   if which gcc > /dev/null 2>&1; then
-                      TARGET=$LINUX_FC2_TARGET
-                         CXX=$LINUX_FC2_CXX
-                          CC=$LINUX_FC2_CC
-                    fi
-                    ;;
-     "Solaris")     if [ -x "$SOLARIS_CC" ]; then
-                      TARGET=$SOLARIS_TARGET
-                         CXX=$SOLARIS_CXX
-                          CC=$SOLARIS_CC
-                    fi
-                    ;;
-     *)             echo "[ERROR] Command failed :"
-                    echo "  Unsupported architecture := \"`uname -sr`\""
-                    fail
-                    exit 1
-                    ;;
+     "Linux.RH71") TARGET=$LINUX_RH71_TARGET
+                      CXX=$LINUX_RH71_CXX
+                       CC=$LINUX_RH71_CC
+                   ;;
+     "Linux.FC2")  TARGET=$LINUX_FC2_TARGET
+                      CXX=$LINUX_FC2_CXX
+                       CC=$LINUX_FC2_CC
+                   ;;
+     "Solaris")    TARGET=$SOLARIS_TARGET
+                      CXX=$SOLARIS_CXX
+                       CC=$SOLARIS_CC
+                   ;;
+     *)            echo "[ERROR] Command failed :"
+                   echo "  Unsupported architecture := \"`uname -sr`\""
+                   fail
+                   exit 1
+                   ;;
    esac
 
    ALLIANCE_TOP="$ALLIANCE_ROOT/$ARCH"
@@ -233,9 +227,8 @@
 
  for ARCH in $ARCHS
  do
-   part "Full ASIM reinstall on Target $TARGET."
-
    guessArch $ARCH
+   part "Full ASIM reinstall on Target $TARGET."
    echo "    ALLIANCE_TOP=$ALLIANCE_TOP"
    echo "          TARGET=$TARGET"
    echo "            ARCH=$ARCH"
@@ -255,6 +248,7 @@
    try grep Alliance_compilation_OK $TARGETLOGFILE
    try rm -rf $DISTRIBDIR/$TMPBUILDDIR/$TARGET
  done
+ try rmdir $DISTRIBDIR/$TMPBUILDDIR
 
 
 )      | perl -ne  '$|=1; printf("%s%s",   "[m", $_)' \
