*** empty log message ***

diff --git a/alliance/src/distrib/mkdistrib b/alliance/src/distrib/mkdistrib
--- a/alliance/src/distrib/mkdistrib
+++ b/alliance/src/distrib/mkdistrib
@@ -4,34 +4,36 @@
 # Copyright (C) 1999, 2000 Czo <Olivier.Sirol@lip6.fr>
 # License: GPL (http://www.gnu.org/copyleft/gpl.html)
 # Started: April 2000
-# Last Change: Thursday 06 June 2002, 14:45
-# Edit Time: 127:43:45
+# Last Change: Tuesday 25 June 2002, 16:08
+# Edit Time: 202:41:33
 # Description:
 #
-# $Id: mkdistrib,v 1.3 2002/06/06 12:46:26 czo Exp $
+# $Id: mkdistrib,v 1.4 2002/06/25 14:09:37 czo Exp $
 #
 
 ###################################################################
+#set -x
+#set -v
 
-DISTRIBDIR=/users/soft5/newlabo/distrib
+ALC_DISTRIBDIR=/users/soft5/newlabo/distrib
 
-WKSLIST="bip beny"
-FTPDISTRIBDIR=/users/largo2/ftp/pub/alliance/unstable/distribution
-LOGFILE=/tmp/albuild.$$
+ALC_WKSLIST="bip beny"
+ALC_FTPDISTRIBDIR=/users/largo2/ftp/pub/alliance/unstable/distribution
+ALC_LOGFILE=/tmp/albuild.$$
 
-DATE=`date +%Y%m%d`
+ALC_RELEASE=`date +%Y%m%d`
 
-ALC_VER="5.0"
-ALC_DIR="alliance-$ALC_VER"
-ALC_PACK="$ALC_DIR-$DATE"
+ALC_VERSION="5.0"
+ALC_DIR="alliance-$ALC_VERSION"
+ALC_PACK="$ALC_DIR-$ALC_RELEASE"
 
 ALC_TMPDIR=tmp-$$
-TMPBUILD=tmpbuild-$$
-TMPINSTALL=tmpinstall-$$
-TMPALLIANCE=alliance-tmp-$$
+ALC_TMPBUILD=tmpbuild-$$
+ALC_TMPINSTALL=tmpinstall-$$
+ALC_TMPALLIANCE=alliance-tmp-$$
 
-TMPDESTDIR=tmpdestdir-$$
-TMPBUILDDIR=tmpbuilddir-$$
+ALC_TMPDESTDIR=tmpdestdir-$$
+ALC_TMPBUILDDIR=tmpbuilddir-$$
 
 CVSROOT=/users/outil/alliance/cvsroot
 export CVSROOT
@@ -75,43 +77,75 @@ echo -e "\
 echo ""
 }
 
-try() {
-$*
+try1() {
+((
+echo "--> TRY $*"
+$* 
 EXECEXIT=$?
 if [ $EXECEXIT != 0 ] ; then 
   fail
-  echo "TRYFAIL $*"
+  echo " <-- ERROR: $*"
   exit $EXECEXIT
 else
-  echo "TRYOK $*"
+  echo " <-- OK: $*"
 fi
+) | perl -ne  'printf("%s%s", "[m", $_)' ) 2>&1 | perl -ne  'printf("%s%s%s", "[1;31;40m", $_, "[m")' 
+}
 
+try() {
+echo "--> TRY $*"
+$* 
+EXECEXIT=$?
+if [ $EXECEXIT != 0 ] ; then 
+  fail
+  echo " <-- ERROR: $*"
+  exit $EXECEXIT
+else
+  echo " <-- OK: $*"
+fi
 }
 
 ###################################################################
-echo "--> mk-distrib"
 
-try cd $DISTRIBDIR
+((
+echo "%%%%%%%%%%%%%%% mk-distrib"
 
-echo "--> Removing old test..."
+try cd $ALC_DISTRIBDIR
+
+echo "%%%%%%%%%%%%%%% Removing old test..."
 mkdir $ALC_TMPDIR
 mv alliance* tmpdestdir-* tmpbuilddir-* $ALC_TMPDIR
 rm -fr  $ALC_TMPDIR &
 
-echo "--> Checkout CVS sources..."
+echo "%%%%%%%%%%%%%%% Checkout CVS sources..."
+if true
+then
 cvs co -P -r TAG_DISTRIB alliance/src
+else
+cvs co -P alliance/src/mbk
+for f in Makefile.am  alliance.m4  autostuff  configure.in  motif.m4  xpm.m4  ylwrap
+do
+cvs co alliance/src/$f
+done
+fi
 
-echo "--> Makedist, generation de alliance-5.0.tar.gz"
+perl -pi -e "s§AC_DEFINE_UNQUOTED.*ALLIANCE_VERSION.*§AC_DEFINE_UNQUOTED(ALLIANCE_VERSION, \"$ALC_VERSION \[$ALC_RELEASE\]\")§" alliance/src/alliance.m4
+
+perl -p -e "s§MYSPEC_VERSION§$ALC_VERSION§ ; s§MYSPEC_RELEASE§$ALC_RELEASE§" alliance/src/distrib/myspec > alliance/src/distrib/alliance.spec
+
+
+echo "%%%%%%%%%%%%%%% Makedist, generation de alliance-5.0.tar.gz"
 
 try cd alliance/src
 
 try ./autostuff
 cd ..
-mkdir $TMPBUILD
-mkdir $TMPINSTALL
-try cd $TMPBUILD
+mkdir $ALC_TMPBUILD
+mkdir $ALC_TMPINSTALL
+try cd $ALC_TMPBUILD
 
-export ALLIANCE_TOP=$DISTRIBDIR/alliance/$TMPINSTALL
+export ALLIANCE_TOP=$ALC_DISTRIBDIR/alliance/$ALC_TMPINSTALL
+export ALLIANCE_TOP
 
 try ../src/configure --prefix=$ALLIANCE_TOP
 
@@ -119,31 +153,42 @@ try make install
 try make distcheck
 
 mv "$ALC_DIR.tar.gz" "$ALC_PACK.tar.gz"
-cp -f "$ALC_PACK.tar.gz" $FTPDISTRIBDIR
 mv -f "$ALC_PACK.tar.gz" ../..
 
 cd ../..
 
-mv alliance $TMPALLIANCE
-(chmod -R 777 $TMPALLIANCE ; rm -fr $TMPALLIANCE)&
+mv alliance $ALC_TMPALLIANCE
+(chmod -R 777 $ALC_TMPALLIANCE ; rm -fr $ALC_TMPALLIANCE)&
 
 try tar -xvzf "$ALC_PACK.tar.gz"
 
-for WKS in $WKSLIST
+ALLIANCE_TOP=/usr/local/alliance
+export ALLIANCE_TOP
+
+for WKS in $ALC_WKSLIST
 do
-
-mkdir $TMPDESTDIR-$WKS $TMPBUILDDIR-$WKS
-ssh -n $WKS "cd $DISTRIBDIR/$TMPBUILDDIR-$WKS ; \
-export ALLIANCE_TOP=$DISTRIBDIR/$TMPDESTDIR-$WKS/usr/local/alliance; \
-echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% $ALLIANCE_TOP" ; \
+try mkdir $ALC_TMPDESTDIR-$WKS $ALC_TMPBUILDDIR-$WKS
+ssh -n $WKS "cd $ALC_DISTRIBDIR/$ALC_TMPBUILDDIR-$WKS ; \
+ALLIANCE_TOP=$ALC_DISTRIBDIR/$ALC_TMPDESTDIR-$WKS/usr/local/alliance ; \
+export ALLIANCE_TOP ; \
 ../$ALC_DIR/configure --prefix=/usr/local/alliance ; \
-make DESTDIR=$ALLIANCE_TOP install"  2>&1 | tee $LOGFILE
-
+gmake DESTDIR=$ALC_DISTRIBDIR/$ALC_TMPDESTDIR-$WKS install && echo Alliance_compilation_OK"  2>&1 | tee $ALC_LOGFILE
+try grep Alliance_compilation_OK $ALC_LOGFILE
+try cd $ALC_DISTRIBDIR/$ALC_TMPDESTDIR-$WKS/usr/local
+try tar chozf $ALC_DISTRIBDIR/$ALC_PACK-$WKS.tar.gz alliance
+try cd $ALC_DISTRIBDIR
 done
 
-echo "done..."
-echo "###########   O K pour tout le monde   #############"
+try mv $ALC_PACK-bip.tar.gz $ALC_PACK-i386-linux-2.4.9.tar.gz
+try mv $ALC_PACK-beny.tar.gz $ALC_PACK-sparc-solaris-2.7.tar.gz
+
+try rpm -ta $ALC_PACK-i386-linux-2.4.9.tar.gz
+
+try cp -f "$ALC_PACK.tar.gz" $ALC_FTPDISTRIBDIR
+try cp -f "$ALC_PACK-i386-linux-2.4.9.tar.gz" $ALC_FTPDISTRIBDIR
+try cp -f "$ALC_PACK-sparc-solaris-2.7.tar.gz" $ALC_FTPDISTRIBDIR
 
 
 
+) | perl -ne  '$|=1; printf("%s%s", "[m", $_)' ) 2>&1 | perl -ne  '$|=1; printf("%s%s%s", "[1;31;40m", $_, "[m")' 
 
